---
- name: Install Ansible collections from requirements.yml
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
