---
- name: Configure VPS with base packages, Docker, Traefik and services
  hosts: vps
  become: true

  roles:
    - role: common
      tags: common

    - role: docker
      tags: docker

    - role: traefik
      tags: traefik

    - role: amneziawg
      tags: amneziawg
