---
- name: Configure VPS with base packages, Docker, Traefik and services
  hosts: vps
  become: true

  roles:
    - role: common
      tags: common

    - role: docker
      tags: docker

    - role: traefik
      tags: traefik

    - role: amnezia
      tags: amnezia

    - role: syncthing
      tags: syncthing

    - role: pocketid
      tags: pocketid

    - role: tinyauth
      tags: tinyauth

    - role: matrix
      tags: matrix

    - role: eturnal
      tags: eturnal

    - role: autoheal
      tags: autoheal

    - role: restic
      tags: restic

    - role: rtc
      tags: rtc
