---
- name: Configure VPS with base packages, Docker, Traefik and services
  hosts: vps
  become: true

  roles:
    # 1. База
    - role: common
      tags: common

    - role: docker
      tags: docker

    # 2. Безопасность и Аутентификация (Фундамент)
    - role: identity
      tags: identity

    # 3. Инфраструктура (Роутинг, Бэкапы, Лечение)
    - role: caddy
      tags: caddy

    - role: autoheal
      tags: autoheal

    - role: restic
      tags: restic

    # 4. Прикладные сервисы
    - role: tuwunel  # Matrix (Зависит от Identity для LDAP)
      tags: tuwunel

    - role: amnezia
      tags: amnezia

    - role: syncthing
      tags: syncthing

    - role: vaultwarden
      tags: vaultwarden

    - role: homepage
      tags: homepage
